// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-discussions/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateMessageService is an autogenerated mock type for the CreateMessageService type
type MockCreateMessageService struct {
	mock.Mock
}

type MockCreateMessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateMessageService) EXPECT() *MockCreateMessageService_Expecter {
	return &MockCreateMessageService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, data
func (_m *MockCreateMessageService) Exec(ctx context.Context, data *models.CreateMessageRequest) (*models.Message, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateMessageRequest) (*models.Message, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateMessageRequest) *models.Message); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateMessageRequest) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateMessageService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCreateMessageService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - data *models.CreateMessageRequest
func (_e *MockCreateMessageService_Expecter) Exec(ctx interface{}, data interface{}) *MockCreateMessageService_Exec_Call {
	return &MockCreateMessageService_Exec_Call{Call: _e.mock.On("Exec", ctx, data)}
}

func (_c *MockCreateMessageService_Exec_Call) Run(run func(ctx context.Context, data *models.CreateMessageRequest)) *MockCreateMessageService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateMessageRequest))
	})
	return _c
}

func (_c *MockCreateMessageService_Exec_Call) Return(_a0 *models.Message, _a1 error) *MockCreateMessageService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateMessageService_Exec_Call) RunAndReturn(run func(context.Context, *models.CreateMessageRequest) (*models.Message, error)) *MockCreateMessageService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateMessageService creates a new instance of MockCreateMessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateMessageService {
	mock := &MockCreateMessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
