// Code generated by mockery v2.49.0. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-discussions/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockGetDiscussionReadStatusService is an autogenerated mock type for the GetDiscussionReadStatusService type
type MockGetDiscussionReadStatusService struct {
	mock.Mock
}

type MockGetDiscussionReadStatusService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetDiscussionReadStatusService) EXPECT() *MockGetDiscussionReadStatusService_Expecter {
	return &MockGetDiscussionReadStatusService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, selector
func (_m *MockGetDiscussionReadStatusService) Exec(ctx context.Context, selector *models.GetDiscussionReadStatusRequest) (*models.DiscussionReadStatus, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.DiscussionReadStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetDiscussionReadStatusRequest) (*models.DiscussionReadStatus, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.GetDiscussionReadStatusRequest) *models.DiscussionReadStatus); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DiscussionReadStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.GetDiscussionReadStatusRequest) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetDiscussionReadStatusService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetDiscussionReadStatusService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - selector *models.GetDiscussionReadStatusRequest
func (_e *MockGetDiscussionReadStatusService_Expecter) Exec(ctx interface{}, selector interface{}) *MockGetDiscussionReadStatusService_Exec_Call {
	return &MockGetDiscussionReadStatusService_Exec_Call{Call: _e.mock.On("Exec", ctx, selector)}
}

func (_c *MockGetDiscussionReadStatusService_Exec_Call) Run(run func(ctx context.Context, selector *models.GetDiscussionReadStatusRequest)) *MockGetDiscussionReadStatusService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GetDiscussionReadStatusRequest))
	})
	return _c
}

func (_c *MockGetDiscussionReadStatusService_Exec_Call) Return(_a0 *models.DiscussionReadStatus, _a1 error) *MockGetDiscussionReadStatusService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetDiscussionReadStatusService_Exec_Call) RunAndReturn(run func(context.Context, *models.GetDiscussionReadStatusRequest) (*models.DiscussionReadStatus, error)) *MockGetDiscussionReadStatusService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetDiscussionReadStatusService creates a new instance of MockGetDiscussionReadStatusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetDiscussionReadStatusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetDiscussionReadStatusService {
	mock := &MockGetDiscussionReadStatusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
