// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-discussions/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetDiscussionReadStatusRepository is an autogenerated mock type for the GetDiscussionReadStatusRepository type
type MockGetDiscussionReadStatusRepository struct {
	mock.Mock
}

type MockGetDiscussionReadStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetDiscussionReadStatusRepository) EXPECT() *MockGetDiscussionReadStatusRepository_Expecter {
	return &MockGetDiscussionReadStatusRepository_Expecter{mock: &_m.Mock}
}

// GetDiscussionReadStatus provides a mock function with given fields: ctx, teamID, userID, target, publicIdentifier
func (_m *MockGetDiscussionReadStatusRepository) GetDiscussionReadStatus(ctx context.Context, teamID string, userID string, target entities.Target, publicIdentifier string) (*entities.ReadStatus, error) {
	ret := _m.Called(ctx, teamID, userID, target, publicIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscussionReadStatus")
	}

	var r0 *entities.ReadStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entities.Target, string) (*entities.ReadStatus, error)); ok {
		return rf(ctx, teamID, userID, target, publicIdentifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entities.Target, string) *entities.ReadStatus); ok {
		r0 = rf(ctx, teamID, userID, target, publicIdentifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.ReadStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, entities.Target, string) error); ok {
		r1 = rf(ctx, teamID, userID, target, publicIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiscussionReadStatus'
type MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call struct {
	*mock.Call
}

// GetDiscussionReadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - userID string
//   - target entities.Target
//   - publicIdentifier string
func (_e *MockGetDiscussionReadStatusRepository_Expecter) GetDiscussionReadStatus(ctx interface{}, teamID interface{}, userID interface{}, target interface{}, publicIdentifier interface{}) *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call {
	return &MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call{Call: _e.mock.On("GetDiscussionReadStatus", ctx, teamID, userID, target, publicIdentifier)}
}

func (_c *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call) Run(run func(ctx context.Context, teamID string, userID string, target entities.Target, publicIdentifier string)) *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(entities.Target), args[4].(string))
	})
	return _c
}

func (_c *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call) Return(_a0 *entities.ReadStatus, _a1 error) *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call) RunAndReturn(run func(context.Context, string, string, entities.Target, string) (*entities.ReadStatus, error)) *MockGetDiscussionReadStatusRepository_GetDiscussionReadStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetDiscussionReadStatusRepository creates a new instance of MockGetDiscussionReadStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetDiscussionReadStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetDiscussionReadStatusRepository {
	mock := &MockGetDiscussionReadStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
