// Code generated by mockery v2.49.0. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-discussions/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetAllMessagesRepository is an autogenerated mock type for the GetAllMessagesRepository type
type MockGetAllMessagesRepository struct {
	mock.Mock
}

type MockGetAllMessagesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetAllMessagesRepository) EXPECT() *MockGetAllMessagesRepository_Expecter {
	return &MockGetAllMessagesRepository_Expecter{mock: &_m.Mock}
}

// GetAllMessages provides a mock function with given fields: ctx, limit, offset
func (_m *MockGetAllMessagesRepository) GetAllMessages(ctx context.Context, limit int64, offset int64) ([]*entities.Message, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMessages")
	}

	var r0 []*entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]*entities.Message, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []*entities.Message); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetAllMessagesRepository_GetAllMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMessages'
type MockGetAllMessagesRepository_GetAllMessages_Call struct {
	*mock.Call
}

// GetAllMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
//   - offset int64
func (_e *MockGetAllMessagesRepository_Expecter) GetAllMessages(ctx interface{}, limit interface{}, offset interface{}) *MockGetAllMessagesRepository_GetAllMessages_Call {
	return &MockGetAllMessagesRepository_GetAllMessages_Call{Call: _e.mock.On("GetAllMessages", ctx, limit, offset)}
}

func (_c *MockGetAllMessagesRepository_GetAllMessages_Call) Run(run func(ctx context.Context, limit int64, offset int64)) *MockGetAllMessagesRepository_GetAllMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockGetAllMessagesRepository_GetAllMessages_Call) Return(_a0 []*entities.Message, _a1 error) *MockGetAllMessagesRepository_GetAllMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetAllMessagesRepository_GetAllMessages_Call) RunAndReturn(run func(context.Context, int64, int64) ([]*entities.Message, error)) *MockGetAllMessagesRepository_GetAllMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetAllMessagesRepository creates a new instance of MockGetAllMessagesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllMessagesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllMessagesRepository {
	mock := &MockGetAllMessagesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
