// Code generated by mockery v2.49.0. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-discussions/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockListDiscussionsByTeamRepository is an autogenerated mock type for the ListDiscussionsByTeamRepository type
type MockListDiscussionsByTeamRepository struct {
	mock.Mock
}

type MockListDiscussionsByTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListDiscussionsByTeamRepository) EXPECT() *MockListDiscussionsByTeamRepository_Expecter {
	return &MockListDiscussionsByTeamRepository_Expecter{mock: &_m.Mock}
}

// ListDiscussionsByTeam provides a mock function with given fields: ctx, teamID, limit, offset
func (_m *MockListDiscussionsByTeamRepository) ListDiscussionsByTeam(ctx context.Context, teamID string, limit int, offset int) ([]*entities.Discussion, error) {
	ret := _m.Called(ctx, teamID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListDiscussionsByTeam")
	}

	var r0 []*entities.Discussion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entities.Discussion, error)); ok {
		return rf(ctx, teamID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entities.Discussion); ok {
		r0 = rf(ctx, teamID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Discussion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, teamID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDiscussionsByTeam'
type MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call struct {
	*mock.Call
}

// ListDiscussionsByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - limit int
//   - offset int
func (_e *MockListDiscussionsByTeamRepository_Expecter) ListDiscussionsByTeam(ctx interface{}, teamID interface{}, limit interface{}, offset interface{}) *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call {
	return &MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call{Call: _e.mock.On("ListDiscussionsByTeam", ctx, teamID, limit, offset)}
}

func (_c *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call) Run(run func(ctx context.Context, teamID string, limit int, offset int)) *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call) Return(_a0 []*entities.Discussion, _a1 error) *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entities.Discussion, error)) *MockListDiscussionsByTeamRepository_ListDiscussionsByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListDiscussionsByTeamRepository creates a new instance of MockListDiscussionsByTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListDiscussionsByTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListDiscussionsByTeamRepository {
	mock := &MockListDiscussionsByTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
