// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-discussions/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockGetDiscussionRepository is an autogenerated mock type for the GetDiscussionRepository type
type MockGetDiscussionRepository struct {
	mock.Mock
}

type MockGetDiscussionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetDiscussionRepository) EXPECT() *MockGetDiscussionRepository_Expecter {
	return &MockGetDiscussionRepository_Expecter{mock: &_m.Mock}
}

// GetDiscussion provides a mock function with given fields: ctx, teamID, publicIdentifier, target, limit, offset
func (_m *MockGetDiscussionRepository) ListDiscussionMessages(ctx context.Context, teamID string, publicIdentifier string, target entities.Target, limit int, offset int) ([]*entities.Message, error) {
	ret := _m.Called(ctx, teamID, publicIdentifier, target, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListDiscussionMessages")
	}

	var r0 []*entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entities.Target, int, int) ([]*entities.Message, error)); ok {
		return rf(ctx, teamID, publicIdentifier, target, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entities.Target, int, int) []*entities.Message); ok {
		r0 = rf(ctx, teamID, publicIdentifier, target, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, entities.Target, int, int) error); ok {
		r1 = rf(ctx, teamID, publicIdentifier, target, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetDiscussionRepository_GetDiscussion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDiscussionMessages'
type MockGetDiscussionRepository_GetDiscussion_Call struct {
	*mock.Call
}

// GetDiscussion is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - publicIdentifier string
//   - target entities.Target
//   - limit int
//   - offset int
func (_e *MockGetDiscussionRepository_Expecter) GetDiscussion(ctx interface{}, teamID interface{}, publicIdentifier interface{}, target interface{}, limit interface{}, offset interface{}) *MockGetDiscussionRepository_GetDiscussion_Call {
	return &MockGetDiscussionRepository_GetDiscussion_Call{Call: _e.mock.On("ListDiscussionMessages", ctx, teamID, publicIdentifier, target, limit, offset)}
}

func (_c *MockGetDiscussionRepository_GetDiscussion_Call) Run(run func(ctx context.Context, teamID string, publicIdentifier string, target entities.Target, limit int, offset int)) *MockGetDiscussionRepository_GetDiscussion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(entities.Target), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockGetDiscussionRepository_GetDiscussion_Call) Return(_a0 []*entities.Message, _a1 error) *MockGetDiscussionRepository_GetDiscussion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetDiscussionRepository_GetDiscussion_Call) RunAndReturn(run func(context.Context, string, string, entities.Target, int, int) ([]*entities.Message, error)) *MockGetDiscussionRepository_GetDiscussion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetDiscussionRepository creates a new instance of MockGetDiscussionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetDiscussionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetDiscussionRepository {
	mock := &MockGetDiscussionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
